#!/usr/bin/env python3
"""
Visualize compare_basecaller_bams.py outputs with matplotlib.

Inputs are the summary.json and per_read_comparison.tsv generated by
validate/compare_basecaller_bams.py. The script writes PNG plots plus a compact
HTML report for quick inspection.
"""

from __future__ import annotations

import csv
import html
import json
import math
from argparse import ArgumentDefaultsHelpFormatter, ArgumentParser
from pathlib import Path
from typing import Dict, Iterable, List, Optional


def require_matplotlib():
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise SystemExit(
            "matplotlib is required for PNG visualization. Install matplotlib "
            "in the active environment, then rerun this script."
        ) from exc
    return plt


def parse_float(value) -> Optional[float]:
    if value is None:
        return None
    text = str(value).strip()
    if text == "" or text.lower() in {"none", "nan", "null"}:
        return None
    try:
        number = float(text)
    except ValueError:
        return None
    if math.isnan(number):
        return None
    return number


def parse_int(value) -> Optional[int]:
    number = parse_float(value)
    if number is None:
        return None
    return int(number)


def clean_values(rows: Iterable[Dict[str, object]], column: str) -> List[float]:
    values = []
    for row in rows:
        value = parse_float(row.get(column))
        if value is not None:
            values.append(value)
    return values


def load_rows(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def load_summary(path: Path) -> Dict[str, object]:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def resolve_inputs(args):
    if args.comparison_dir:
        comparison_dir = Path(args.comparison_dir)
        per_read_tsv = args.per_read_tsv or comparison_dir / "per_read_comparison.tsv"
        summary_json = args.summary_json or comparison_dir / "summary.json"
    else:
        per_read_tsv = args.per_read_tsv
        summary_json = args.summary_json

    if per_read_tsv is None or summary_json is None:
        raise SystemExit(
            "Provide --comparison-dir, or provide both --per-read-tsv and --summary-json."
        )
    return Path(per_read_tsv), Path(summary_json)


def save_overview_plot(rows: List[Dict[str, str]], summary: Dict[str, object], out_dir: Path):
    plt = require_matplotlib()
    identities = clean_values(rows, "identity")
    edit_distances = clean_values(rows, "edit_distance")
    tetra_lengths = clean_values(rows, "tetramod_length")
    bonito_lengths = clean_values(rows, "bonito_length")
    qscore_deltas = clean_values(rows, "qscore_delta_tetramod_minus_bonito")

    fig, axes = plt.subplots(2, 2, figsize=(12, 9))
    fig.suptitle("Basecaller BAM comparison overview", fontsize=14)

    ax = axes[0][0]
    ax.hist(identities, bins=40, color="#2c7fb8", edgecolor="white")
    ax.set_xlabel("Sequence identity")
    ax.set_ylabel("Read count")
    ax.set_xlim(0, 1)
    ax.grid(alpha=0.2)

    ax = axes[0][1]
    ax.hist(edit_distances, bins=40, color="#f03b20", edgecolor="white")
    ax.set_xlabel("Edit distance")
    ax.set_ylabel("Read count")
    ax.grid(alpha=0.2)

    ax = axes[1][0]
    ax.scatter(bonito_lengths, tetra_lengths, s=14, alpha=0.55, color="#31a354")
    if bonito_lengths and tetra_lengths:
        max_len = max(max(bonito_lengths), max(tetra_lengths))
        ax.plot([0, max_len], [0, max_len], color="#555555", linewidth=1)
    ax.set_xlabel("Bonito read length")
    ax.set_ylabel("TetraMod read length")
    ax.grid(alpha=0.2)

    ax = axes[1][1]
    ax.hist(qscore_deltas, bins=40, color="#756bb1", edgecolor="white")
    ax.axvline(0, color="#555555", linewidth=1)
    ax.set_xlabel("Mean Q-score delta (TetraMod - Bonito)")
    ax.set_ylabel("Read count")
    ax.grid(alpha=0.2)

    metrics = summary.get("metrics", {})
    footer = (
        f"mean identity={metrics.get('mean_identity', 'NA')} | "
        f"mean edit distance={metrics.get('mean_edit_distance', 'NA')} | "
        f"mean length delta={metrics.get('mean_length_delta', 'NA')} | "
        f"mean qscore delta={metrics.get('mean_qscore_delta', 'NA')}"
    )
    fig.text(0.5, 0.01, footer, ha="center", fontsize=9)
    fig.tight_layout(rect=(0, 0.03, 1, 0.96))

    path = out_dir / "overview.png"
    fig.savefig(path, dpi=160)
    plt.close(fig)
    return path


def save_error_breakdown_plot(rows: List[Dict[str, str]], out_dir: Path):
    plt = require_matplotlib()
    labels = [
        ("matches", "Matches"),
        ("mismatches", "Mismatches"),
        ("insertions_vs_bonito", "Insertions vs Bonito"),
        ("deletions_vs_bonito", "Deletions vs Bonito"),
    ]
    values = [sum(clean_values(rows, column)) for column, _ in labels]

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.bar(
        [label for _, label in labels],
        values,
        color=["#31a354", "#f03b20", "#fd8d3c", "#756bb1"],
    )
    ax.set_ylabel("Total aligned bases/events")
    ax.set_title("Sequence comparison event totals")
    ax.grid(axis="y", alpha=0.2)
    fig.tight_layout()

    path = out_dir / "event_totals.png"
    fig.savefig(path, dpi=160)
    plt.close(fig)
    return path


def save_mapping_plot(rows: List[Dict[str, str]], out_dir: Path):
    plt = require_matplotlib()
    labels = [
        "TetraMod mapped",
        "TetraMod unmapped",
        "Bonito mapped",
        "Bonito unmapped",
    ]
    values = [
        sum(1 for row in rows if parse_int(row.get("tetramod_is_unmapped")) == 0),
        sum(1 for row in rows if parse_int(row.get("tetramod_is_unmapped")) == 1),
        sum(1 for row in rows if parse_int(row.get("bonito_is_unmapped")) == 0),
        sum(1 for row in rows if parse_int(row.get("bonito_is_unmapped")) == 1),
    ]

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.bar(labels, values, color=["#31a354", "#f03b20", "#31a354", "#f03b20"])
    ax.set_ylabel("Read count")
    ax.set_title("Mapping status on shared reads")
    ax.tick_params(axis="x", labelrotation=20)
    ax.grid(axis="y", alpha=0.2)
    fig.tight_layout()

    path = out_dir / "mapping_status.png"
    fig.savefig(path, dpi=160)
    plt.close(fig)
    return path


def format_metric(value) -> str:
    if isinstance(value, float):
        return f"{value:.6g}"
    return html.escape(str(value))


def metric_table(summary: Dict[str, object]) -> str:
    rows = []
    for section in ("counts", "metrics"):
        values = summary.get(section, {})
        if not isinstance(values, dict):
            continue
        rows.append(f'<tr><th colspan="2">{html.escape(section)}</th></tr>')
        for key, value in values.items():
            rows.append(
                "<tr>"
                f"<td>{html.escape(str(key))}</td>"
                f"<td>{format_metric(value)}</td>"
                "</tr>"
            )
    return "\n".join(rows)


def worst_read_table(rows: List[Dict[str, str]], limit: int) -> str:
    columns = [
        "read_id",
        "identity",
        "edit_distance",
        "tetramod_length",
        "bonito_length",
        "length_delta_tetramod_minus_bonito",
        "tetramod_mean_qscore",
        "bonito_mean_qscore",
        "qscore_delta_tetramod_minus_bonito",
        "tetramod_is_unmapped",
        "bonito_is_unmapped",
    ]
    sorted_rows = sorted(
        rows,
        key=lambda row: (
            parse_float(row.get("identity")) if parse_float(row.get("identity")) is not None else 1.0,
            -(parse_float(row.get("edit_distance")) or 0.0),
        ),
    )
    header = "".join(f"<th>{html.escape(column)}</th>" for column in columns)
    body = []
    for row in sorted_rows[:limit]:
        body.append(
            "<tr>"
            + "".join(f"<td>{html.escape(str(row.get(column, '')))}</td>" for column in columns)
            + "</tr>"
        )
    return f"<table><thead><tr>{header}</tr></thead><tbody>{''.join(body)}</tbody></table>"


def save_html_report(
    rows: List[Dict[str, str]],
    summary: Dict[str, object],
    plot_paths: List[Path],
    out_dir: Path,
    *,
    worst_read_limit: int,
):
    inputs = [
        ("TetraMod BAM", summary.get("tetramod_bam", "")),
        ("Bonito BAM", summary.get("bonito_bam", "")),
    ]
    input_items = "\n".join(
        f"<li><strong>{html.escape(label)}:</strong> {html.escape(str(value))}</li>"
        for label, value in inputs
    )
    plot_items = "\n".join(
        f"<section><h2>{html.escape(path.stem.replace('_', ' ').title())}</h2>"
        f'<img src="{html.escape(path.name)}" alt="{html.escape(path.stem)}"></section>'
        for path in plot_paths
    )
    document = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Basecaller BAM comparison report</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 24px; color: #222; }}
    h1, h2 {{ margin-bottom: 0.35rem; }}
    img {{ max-width: 100%; border: 1px solid #ddd; }}
    table {{ border-collapse: collapse; width: 100%; margin: 12px 0 24px; font-size: 13px; }}
    th, td {{ border: 1px solid #ddd; padding: 6px 8px; text-align: left; }}
    th {{ background: #f5f5f5; }}
    section {{ margin: 28px 0; }}
  </style>
</head>
<body>
  <h1>Basecaller BAM comparison report</h1>
  <ul>{input_items}</ul>
  <h2>Summary</h2>
  <table>{metric_table(summary)}</table>
  {plot_items}
  <h2>Lowest identity reads</h2>
  {worst_read_table(rows, worst_read_limit)}
</body>
</html>
"""
    path = out_dir / "report.html"
    path.write_text(document, encoding="utf-8")
    return path


def main(args) -> None:
    per_read_tsv, summary_json = resolve_inputs(args)
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    rows = load_rows(per_read_tsv)
    summary = load_summary(summary_json)
    if not rows:
        raise SystemExit(f"No per-read rows found in {per_read_tsv}")

    plot_paths = [
        save_overview_plot(rows, summary, out_dir),
        save_error_breakdown_plot(rows, out_dir),
        save_mapping_plot(rows, out_dir),
    ]
    report_path = save_html_report(
        rows,
        summary,
        plot_paths,
        out_dir,
        worst_read_limit=args.worst_read_limit,
    )

    print(f"loaded rows: {len(rows)}")
    print(f"png plots written to: {out_dir}")
    print(f"html report: {report_path}")


def argparser() -> ArgumentParser:
    parser = ArgumentParser(formatter_class=ArgumentDefaultsHelpFormatter)
    parser.add_argument(
        "--comparison-dir",
        type=Path,
        help="Directory containing per_read_comparison.tsv and summary.json.",
    )
    parser.add_argument(
        "--per-read-tsv",
        type=Path,
        help="Path to per_read_comparison.tsv. Overrides --comparison-dir default.",
    )
    parser.add_argument(
        "--summary-json",
        type=Path,
        help="Path to summary.json. Overrides --comparison-dir default.",
    )
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--worst-read-limit", type=int, default=30)
    return parser


if __name__ == "__main__":
    main(argparser().parse_args())
